ports:
  - port: 5000
    onOpen: open-preview

image:
  file: .gitpod.Dockerfile

tasks:
  - before: |
      export FLASK_APP=flaskr
      export FLASK_ENV=development
      export LANG=en_US.utf8
      export LC_ALL=en_US.utf8
    command: |
      sudo pip3 install -e .
      flask init-db
      flask run

vscode:
  extensions:
    - ms-python.python
